baseURL = "/"
languageCode = "fr-fr"
title = "Solal Gendrin"
theme = "blank"
paginate= 100
[taxonomies]
	tag = "tags"

[menu]

  [[menu.main]]
    identifier = "tout"
    name = "Tout"
    url = "/"
    weight = -10

  [[menu.main]]
    identifier = "experience#menu"
    name = "Experiences"
    url = "/tags/experience/"
    weight = -9

  [[menu.main]]
    identifier = "formation#menu"
    name = "Formations"
    url = "/tags/formation/"
    weight = -8

  [[menu.main]]
    identifier = "evolution#menu"
    name = "Ã‰volutions"
    url = "/tags/evolution/"
    weight = -7

  [[menu.main]]
    identifier = "article#menu"
    name = "Articles"
    url = "/tags/article"
    weight = -6